In [1]:
import logging
import pandas as pd
import pickle

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

from src.constants.constants import FEATURES_PATH, MODELS_PATH

In [35]:
ft_imp_sel = ['macd_histogram',
 'macd',
 'close_lag_7',
 'close_lag_5',
 'sma_50',
 'bb_width',
 'atr_14',
 'bb_upper',
 'price_diff_4',
 'pct_change_6']

In [36]:
X_train = pd.read_parquet(FEATURES_PATH / "X_train_scaled.parquet")[ft_imp_sel]
y_train = pd.read_parquet(FEATURES_PATH / "y_train.parquet")['target']

In [37]:
X_train.head(2)

,macd_histogram,macd,close_lag_7,close_lag_5,sma_50,bb_width,atr_14,bb_upper,price_diff_4,pct_change_6
0,-0.850013,-0.715491,-2.153488,-2.288019,-1.939454,-0.480648,-0.990381,-2.183643,-1.325126,-1.697647
1,-0.944202,-0.804216,-2.162296,-2.181776,-1.954108,-0.313796,-0.974313,-2.166142,-0.866778,-1.150842

In [38]:
# X_train.columns

In [40]:
X_test = pd.read_parquet(FEATURES_PATH / "X_test_scaled.parquet")[ft_imp_sel]
y_test = pd.read_parquet(FEATURES_PATH / "y_test.parquet")['target']

In [8]:
model = LogisticRegression(
    max_iter=100,
    random_state=42,
    n_jobs=1,
    fit_intercept=True,
    class_weight='balanced'  # Para manejar desbalance de clases
)

In [49]:
model = GradientBoostingClassifier(
    n_estimators=5,
    learning_rate=0.8,
    max_depth=6,
    min_samples_split=15,
    min_samples_leaf=10,
    random_state=42,
    warm_start=True,
    verbose=0,
    subsample=0.6,
    validation_fraction=0.2,
)

In [57]:
model = RandomForestClassifier(
    n_estimators=10,
    max_depth=5,
    min_samples_split=0.05,
    min_samples_leaf=0.01,
    random_state=42,
    class_weight='balanced',
    warm_start=False,
    max_features=0.9,
    oob_score=True,
    n_jobs=1
)

In [58]:
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)

train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred)
train_recall = recall_score(y_train, y_train_pred)
train_f1 = f1_score(y_train, y_train_pred)

/Users/errodringer/Proyectos/ia_btc_forecast/.venv/lib/python3.12/site-packages/sklearn/ensemble/_forest.py:615: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

In [59]:
print(f"✅ Modelo entrenado")
print(f"📊 Métricas en TRAIN:")
print(f"   Accuracy: {train_accuracy:.4f}")
print(f"   Precision: {train_precision:.4f}")
print(f"   Recall: {train_recall:.4f}")
print(f"   F1-Score: {train_f1:.4f}")

✅ Modelo entrenado
📊 Métricas en TRAIN:
   Accuracy: 0.7071
   Precision: 0.7454
   Recall: 0.6545
   F1-Score: 0.6970

In [60]:
# Predicciones
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

# df_preds = pd.DataFrame({"y_test": y_test, "y_pred": y_pred, "y_proba": y_proba})

# y_pred = [1 if x > 0.55 else 0 for x in df_preds.y_proba]

# Métricas
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_proba)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(f"📊 Métricas en TEST:")
print(f"   Accuracy: {accuracy:.4f}")
print(f"   Precision: {precision:.4f}")
print(f"   Recall: {recall:.4f}")
print(f"   F1-Score: {f1:.4f}")
print(f"   ROC-AUC: {roc_auc:.4f}")
print(f"\n📊 Confusion Matrix:")
print(f"   TN: {cm[0,0]}  FP: {cm[0,1]}")
print(f"   FN: {cm[1,0]}  TP: {cm[1,1]}")

📊 Métricas en TEST:
   Accuracy: 0.4815
   Precision: 0.4375
   Recall: 0.5833
   F1-Score: 0.5000
   ROC-AUC: 0.4944

📊 Confusion Matrix:
   TN: 12  FP: 18
   FN: 10  TP: 14

In [53]:
df_imp = pd.DataFrame({"feature": X_train.columns, "imp": model.feature_importances_}).sort_values("imp", ascending=False)

In [54]:
df_imp.head(10).feature.tolist()

['close_lag_5',
 'price_diff_4',
 'pct_change_6',
 'macd_histogram',
 'sma_50',
 'bb_width',
 'atr_14',
 'macd',
 'close_lag_7',
 'bb_upper']

In [55]:
df_preds = pd.DataFrame({"y_test": y_test, "y_pred": y_pred, "y_proba": y_proba})

In [56]:
df_preds.tail(10)

    y_test  y_pred   y_proba
44       0       0  0.366257
45       0       0  0.026969
46       1       0  0.115528
47       1       0  0.023530
48       0       0  0.324013
49       1       1  0.923744
50       0       1  0.832835
51       0       1  0.979714
52       1       1  0.589101
53       1       1  0.543596

In [243]:
df_preds.head(10)

   y_test  y_pred   y_proba
0       0       0  0.485039
1       1       0  0.485039
2       0       0  0.485039
3       1       0  0.485039
4       1       0  0.485039
5       1       0  0.485039
6       1       0  0.485039
7       1       0  0.485039
8       0       0  0.485039
9       0       0  0.485039

In [24]:
df_preds.y_proba.max()

0.8539022778266749

In [132]:
df_preds[df_preds.y_proba > 0.7]

    y_test  y_pred  y_proba
37       0       1  0.71004